---
title: "Cross G-function"
author: "Enrico Lucci"
date: "2022-10-08"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import libraries, message=FALSE, warning=FALSE, include=FALSE}

library(readxl)
library(spatstat)
library(foreach)
library(ggplot2)

```

```{r import dataset, message=FALSE, warning=FALSE, include=FALSE}

Cumulative_dataset <- library(readxl)
Cumulative_dataset <- read_excel("Cumulative_dataset.xlsx", 
    col_types = c("text", "numeric", "numeric", 
        "text"))
View(Cumulative_dataset)

ggplot(Cumulative_dataset, aes(Cumulative_dataset$x, Cumulative_dataset$y, 
                               color = Cumulative_dataset$type)) + 
   geom_point(size=0.3)

Categories = c("S/G I-II","S/G III-IV","C I-II","C III-IV","P I-II",
               "P III-IV","D I-II", "D III-IV", "L-tools","L-Flakes", "L-cores", "Ant/bones","Tortoise", "Metal","Fish","Bird")


# creation of ppp


remains = ppp(Cumulative_dataset$x, Cumulative_dataset$y,  
              marks = factor(Cumulative_dataset$type),
              window=owin(c(111.76,146.76),c(86.08,101.06)),
              unitname=c("metre","metres"))



```

## Entire area

```{r Entire area, echo=FALSE, message=FALSE, warning=FALSE}

par(mfrow=c(2,4))

foreach(x1 = 1:16) %:%
  foreach(x2 = 1:16) %do% {
    
    A = Categories[x1]
    B = Categories[x2]
    
    GAB_ea= Gcross(remains,A,B)
    plot(GAB_ea, main = NULL, legend = FALSE)
  }

```

## Sample area: F3C

```{r F3C, echo=FALSE, message=FALSE, warning=FALSE}

remainsF3C = ppp(Cumulative_dataset$x, Cumulative_dataset$y,  
              marks = factor(Cumulative_dataset$type),
              window=owin(c(117.288411578099996,122.288411578099996),
                          c(91.285849357999993,96.285849357999993)),
              unitname=c("metre","metres"))

plot(remainsF3C, main = "F3C", cex = 0.7, legend = F, 
     pch = 19, col = "lightyellow")


par(mfrow=c(2,4))

foreach(x1 = 1:16) %:%
  foreach(x2 = 1:16) %do% {
    
    A = Categories[x1]
    B = Categories[x2]
    
    GAB_F3C= Gcross(remainsF3C,A,B)
    plot(GAB_F3C, main = NULL, legend = FALSE)
  }



```

## Sample area: G2O-G3A

```{r G2O G3A, echo=FALSE, message=FALSE, warning=FALSE}


remainsG2O_G3A = ppp(Cumulative_dataset$x, Cumulative_dataset$y,  
                 marks = factor(Cumulative_dataset$type),
                 window=owin(c(127.288411578099996,132.288411578100011),
                             c(91.285849357999993,101.285849357999993)),
                 unitname=c("metre","metres"))
plot(remainsG2O_G3A, main = "G2O-G3A", cex = 0.7, legend = F, pch = 19, col = "lightblue")


par(mfrow=c(2,4))

foreach(x1 = 1:16) %:%
  foreach(x2 = 1:16) %do% {
    
    A = Categories[x1]
    B = Categories[x2]
    
    GAB_G20G3A= Gcross(remainsG2O_G3A,A,B)
    plot(GAB_G20G3A, main = NULL, legend = FALSE)
  }

```

## Sample area: G3B-G3C

```{r G3B G3C, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

remainsG3B_G3C = ppp(Cumulative_dataset$x, Cumulative_dataset$y,  
                     marks = factor(Cumulative_dataset$type),
                     window=owin(c(132.288411578100011,142.288411578100011),
                                 c(91.285849357999993,96.285849357999993)),
                     unitname=c("metre","metres"))
plot(remainsG3B_G3C, main = "G3B-G3C", cex = 0.7, legend = F, pch = 19, col = "lightgreen")

par(mfrow=c(2,4))

foreach(x1 = 1:16) %:%
  foreach(x2 = 1:16) %do% {
    
    A = Categories[x1]
    B = Categories[x2]
    
    GAB_G3BG3C= Gcross(remainsG3B_G3C,A,B)
    plot(GAB_G3BG3C, main = NULL, legend = FALSE)
  }


```
